### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by pedro45-vs** [G33kDude/cJson.ahk#10]
Is it a bug or deliberate? How to achieve consistent output?

```
MsgBox JSON.Dump(['pão', 'à', 'chapéu', 'vô'], 0)

; Result: ["p\u00E3o","\u00E0","chap\u00E9u","v\u00F4","cal\u00E7\u00E3o"]
```

**Comment by G33kDude** [comment]
This is, as you call it, intentional. It is done for improved compatibility with systems that tamper with document encodings. Notably, AutoHotkey's own file commands operate in ANSI ending by default, so this allows reading and writing JSON containing unicode characters with default file settings in AHK. It is also the approach taken by Python.

You can disable the escaping of unicode characters by setting `JSON.EscapeUnicode := false`.
